config/routes.rb
Inkreactor::Application.routes.draw do
  
  root 'static_pages#welcome'

  devise_for :users
  resources :users, only: [:show]
  resources :tags, only: [:index]
	get 'tags/:name', to: 'tags#show', as: 'tag'

  resources :posts, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :tags, :only => [:new, :create]
    resources :comments, :only => [:new, :create, :edit, :update]
  end

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates_presence_of :content
end

app/models/post.rb
class Post < ActiveRecord::Base
  CONTENT_MAX_LENGTH = 8000
  SUBJECT_MAX_LENGTH = 50
  PER_PAGE = 25

  validates :subject, :content, :presence => true

  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :tags
  validates_length_of :content, maximum: CONTENT_MAX_LENGTH
  validates_length_of :subject, maximum: SUBJECT_MAX_LENGTH

  def owner? user
    self.user == user
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :posts

	validates :name, presence: true, length: { minimum: 1 }

	def to_param
  	name.parameterize
	end

	def self.posts_tagged_with(tag_name)
		self.find_by_name(tag_name).posts
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username

  validates :email, format: { with: /.{1,}@.{1,}\..{1,}/,
    message: "must be a valid email address"}

  has_many :posts
  has_many :comments

end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
	belongs_to :post

	validates_presence_of :user_id
	validates_presence_of :post_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:username, :email, :password)}
  end

  #overrides devise redirect after sign-in
  def after_sign_in_path_for(resource)
    posts_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.build(comment_params)
    if comment.save
      redirect_to post_path(post)
    else
      render :new
    end
  end

  # REVIEW: handle unhappy path
  def edit
    @post = Post.find_by_id(params[:post_id])
    @comment = Comment.find_by_id(params[:id])
    render :json => {
      edit_template: render_to_string(:partial => 'coments/form',
                                      :locals => {post: @post, comment: @comment})
      }
  end

  def update
    Comment.find_by_id(params[:id]).update(comment_params)
    redirect_to post_path(params[:post_id])
  end

  private

  def comment_params
    params.required(:comment).permit(:content)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_and_authorize_post, :only => [:edit, :update, :destroy]
  def index
    @posts = Post.limit(Post::PER_PAGE)  #Do we want to limit the number of posts, or paginate?
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build post_params
    if @post.save
      redirect_to post_path(post)
    else
      render :new
    end
  end

  def show
    @post = Post.find_by_id(params[:id])
    @comment = Comment.new(post_id: @post.id)
		@tag = Tag.new
		@tag.posts << @post
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      redirect_to edit_post_path(@post)
    end
  end

  def destroy
    if @post.user == current_user
      @post.destroy
      flash[:success] = "Post \"#{post.subject}\" was deleted."
      redirect_to posts_path
    else
      render 'public/401', status: :unauthorized
    end
  end

  private

  def post_params
    params.require(:post).permit(:subject, :content)
  end

  def load_and_authorize_post
    @post = Post.find_by_id(params[:id])
    redirect_to root_path unless @post.owner? current_user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def welcome
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_filter :load_post!, only: [:create, :new]
  def index
    @tags = Tag.all
  end

  # REVIEW: don't render posts/index, create a tags/show template that render a shared partial.
	def show
		@posts = Tag.posts_tagged_with(params[:name])
		@tag = Tag.find_by_name(params[:name])
		render 'posts/index'
	end

	def new
		@tag = @post.tags.new
		render :_new
	end

	def create
		tag = Tag.find_by_name(tag_params[:name])
		if tag
			@post.tags.push(tag)
		else
			@post.tags.create(tag_params)
		end
		redirect_to post_path(@post)
  end

	private
	def load_post!
		@post = Post.find(params[:post_id])
	end

  def tag_params
		params.require(:tag).permit([:name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by_id(params[:id])
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	before_filter :authenticate_user

  def new
  	@vote = Votes.new
  end

  def create
  	post = Post.find(params[:post_id])
  	post.votes.create(:upvote => true)
  	redirect_to_post_path(post)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment], html: { class: 'comment-form'} do |f| %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head profile="http://www.inkreactor.com">
  <title>Inkreactor</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "layout", media: "all", "data-turbolinks-track" => true %>
  // REVIEW: require this file in application.js and move it from here.
  <%= javascript_include_tag "vendor/custom.modernizr" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Bilbo+Swash+Caps|Gilda+Display|Bad+Script|Trykker|Poly|Actor' rel='stylesheet' type='text/css'>

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>

<div id='container' class='row'>
  <nav id='left_column_nav' class="small-2 columns">
    <ul class="side-nav">
    // REVIEW: move this to a partial
      <li><%if !current_user%><%=link_to "Sign In", user_session_path %><%end%></li>
      <li><%if !current_user%><%=link_to "Sign Up", new_user_registration_path%><%end%></li>
      <li><%if current_user%><%=link_to "Sign Out", destroy_user_session_path, :method =>:delete %><%end%></li>


      <li class="nav_bar_divider"></li>
      // REVIEW: move this to a partial
      <li><a data-dropdown="drop1">Post</a>
          <ul id="drop1" class="f-dropdown" data-dropdown-content>
            <li><a href="#"></a></li>
            <li><%=link_to "View Post", posts_path%></li>
            <li><%=link_to "Create Post", new_post_path%></li>
          </ul>
      </li>
    </ul>

    <footer>
      <div id="social-icons">
        <a href="https://facebook.com"><%= image_tag 'facebook.png', size: '24x24' %></a>
        <a href="https://twitter.com"><%= image_tag 'twitter.png', size: '24x24' %></a>
        <a href="https://github.com"><%= image_tag 'github.png', size: '24x24' %></a>
      </div>
        <p>Created by:</p>
        <a href="mailto:seth@sethhochberg.com">Seth, </a>
        <a href="mailto:stharlow@gmail.com">Steve, </a>
        <a href="mailto:dewrgleision@gmail.com">Dan, </a>
        <a href="mailto:mehagel65@gmai.com">Mark</a>
    </footer>
  </nav>
  <div id='content' class='small-10 columns'>
    <% flash.each do |key,msg| %>
  		<div class="message" id="<%= key %>">
    		<div class="message-inner">
      	<%= content_tag :p, msg %>
    		</div>
  		</div>
		<% end %>


		<%= yield %>
  </div>
</div>

<div class="reveal-modal"></div>
</body>
</html>

app/views/posts/_comment_template.html.erb
<%= comment.content %>

app/views/posts/_form.html.erb
<%= render 'form_errors', :object => @post %>
<%= form_for @post do |f| %>
  <%= f.label :subject, "Subject" %>
  <%= f.text_area :subject %>
  <%= f.label :content, "Content" %>
  <%= f.text_area :content %>
  <%= f.submit "Submit", data: { :disable_with => 'Submiting...' } %>
<% end %>

app/views/posts/edit.html.erb
<div>
  <%= render 'posts/form' %>
</div>

app/views/posts/index.html.erb
<% if @tag %>
	<h1>Posts tagged with <%= @tag.name %></h1>
<% else %>
	<h1>Posts</h1>
<% end %>
<% @posts.each do |post| %>
  <h4><%= link_to post.subject, post_path(post) %></h4>
<% end %>
<hr />
<%= link_to "Add New Post", new_post_path %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
<%= f.label :subject, "Subject" %>
<%= f.text_area :subject %>
<%= f.label :content, "Content" %>
<%= f.text_area :content %>
<%= f.submit "Submit", :disable_with => 'Submiting...' %>
<% end %> 

app/views/posts/show.html.erb
<div>
  <h1><%= @post.subject %></h1>
  <p><%= @post.content %></p>
  <%= link_to 'Delete Post', post_path(@post), method: :delete %>
</div>
<div class="post-tags">
	<h4>Post Tags:</h4>
	<% @post.tags.each do |tag| %>
		<span><%= link_to tag.name, tag_path(tag) %></span>
	<% end %>
	<div class="tag-form">
		<%= render partial: 'tags/new' %>
	</div>
</div>
<hr />
<div>
	<h4>Comments:</h4>
  <div>
  	<%= render partial: 'comments/form' %>
	</div>
	<ul>
    <% @post.comments.each do |comment| %>
      <li id="comment-<%= comment.id %>", class='get-edit-comment'>
        <%= render '/posts/comment_template', comment: comment %></br>
        <%= link_to 'edit', edit_post_comment_path(@post, comment), remote: true %> 
      </li>
    <% end %>
  </ul>
</div>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messsages.each do |error|%>
    <%= error %>
  <% end %>
<% end %>

app/views/static_pages/welcome.html.erb
<h4>Welcome to InkReactor</h4>

app/views/tags/_new.html.erb
<%= form_for [@post, @tag] do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/tags/index.html.erb
<div id="tag-list">
	<% @tags.each do |tag|%>
		<h3><%= link_to tag.name, tag %></h3>
	<% end %>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>